// <auto-generated />
using System;
using CameraDataWebApp.Controllers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CameraDataWebApp.Migrations
{
    [DbContext(typeof(ObservationContext))]
    [Migration("20190208091323_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CameraDataWebApp.Controllers.MonitoringVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("casename");

                    b.Property<string>("casenumber");

                    b.Property<string>("visitguid");

                    b.Property<string>("visitname");

                    b.HasKey("Id");

                    b.ToTable("MonitoringVisits");
                });

            modelBuilder.Entity("CameraDataWebApp.Controllers.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MonitoringVisitId");

                    b.Property<string>("imageuri");

                    b.Property<string>("observation");

                    b.Property<string>("observationguid");

                    b.Property<string>("visitguid");

                    b.Property<string>("visitname");

                    b.HasKey("Id");

                    b.HasIndex("MonitoringVisitId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("CameraDataWebApp.Controllers.Observation", b =>
                {
                    b.HasOne("CameraDataWebApp.Controllers.MonitoringVisit")
                        .WithMany("observations")
                        .HasForeignKey("MonitoringVisitId");
                });
#pragma warning restore 612, 618
        }
    }
}
